'use client'
import { useMemo, useState } from 'react'
const factors:Record<string,number>={local:.85,service:1,ecommerce:.72,coach:1.08,gastro:.65,realestate:1.15}
export function ROICalculator(){
 const [industry,setIndustry]=useState('service'),[revenue,setRevenue]=useState(25000),[value,setValue]=useState(1800),[customers,setCustomers]=useState(5),[months,setMonths]=useState(6)
 const result=useMemo(()=>{const won=Math.max(1,Math.round(customers*months*factors[industry]));const extra=won*value;const invest=months*2490;const profit=extra-invest;const roi=Math.round((profit/invest)*100);const growth=Math.round((extra/(revenue*months))*100);const breakeven=Math.max(1,Math.ceil(invest/Math.max(1,value*customers*factors[industry])));return{won,extra,invest,profit,roi,growth,breakeven}},[industry,revenue,value,customers,months])
 const money=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n)
 return <div className="roi-grid"><div className="roi-card reveal"><div className="field"><label>Wähle deine Branche</label><div className="choice-row">{[['local','Lokales Geschäft'],['service','Dienstleister'],['ecommerce','E-Commerce'],['coach','Coach / Berater'],['gastro','Gastronomie'],['realestate','Immobilien']].map(([key,label])=><button key={key} className={`choice ${industry===key?'active':''}`} onClick={()=>setIndustry(key)}>{label}</button>)}</div></div><div className="field"><label>Aktueller Monatsumsatz</label><input type="number" value={revenue} min="0" onChange={e=>setRevenue(Number(e.target.value))}/></div><div className="field"><label>Verdienst pro Neukunde</label><input type="number" value={value} min="0" onChange={e=>setValue(Number(e.target.value))}/></div><div className="field"><label>Gewünschte Neukunden pro Monat: {customers}</label><input type="range" value={customers} min="1" max="30" onChange={e=>setCustomers(Number(e.target.value))}/></div><div className="field"><label>Zeitraum</label><div className="choice-row">{[3,6,12].map(m=><button key={m} className={`choice ${months===m?'active':''}`} onClick={()=>setMonths(m)}>{m} Monate</button>)}</div></div></div><div className="roi-card reveal"><span className="eyebrow">Dein potenzielles Ergebnis</span><div className="roi-value">{result.roi>0?'+':''}{result.roi}%</div><span>modellierter Return on Investment nach Agenturkosten</span><div className="metrics"><div className="metric"><span>Neukunden</span><strong>{result.won}</strong></div><div className="metric"><span>Zusatzumsatz</span><strong>{money(result.extra)}</strong></div><div className="metric"><span>Investition</span><strong>{money(result.invest)}</strong></div><div className="metric"><span>Nettogewinn</span><strong>{money(result.profit)}</strong></div><div className="metric"><span>Break-even</span><strong>Monat {result.breakeven}</strong></div><div className="metric"><span>Wachstum</span><strong>+{result.growth}%</strong></div></div><p className="cms-note">Modellrechnung, keine Ergebnisgarantie.</p></div></div>
}
