import Link from 'next/link'
import { JsonLd } from '@/components/site/JsonLd'
import { growthMethod } from '@/lib/siteContent'
import { buildMetadata } from '@/lib/seo'

export const metadata = buildMetadata({ title: 'JJ Growth System – Social Media mit Methode', description: 'Die JJ-Media Methode verbindet Diagnose, Positionierung, Creative, Distribution und kontinuierliche Optimierung zu einem messbaren Social-Media-System.', path: '/methode' })

export default function MethodPage() {
  const schema = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'JJ Growth System', step: growthMethod.map((step) => ({ '@type': 'HowToStep', position: Number(step.number), name: step.name, text: step.promise })) }
  return <><JsonLd data={schema}/><header className="inner-hero method-hero"><div className="container inner-hero-grid"><div><span className="availability reveal"><i/>Die JJ-Media Methode</span><h1 className="premium-display reveal">Kein Content-Chaos.<br/><em>Ein System mit Lernkurve.</em></h1></div><div className="inner-hero-aside reveal"><p>Das JJ Growth System verbindet strategische Klarheit, kreative Umsetzung und messbare Distribution. Jede Phase produziert konkrete Entscheidungen und verwertbare Ergebnisse.</p><Link className="btn btn-coral" href="/social-media-audit">Social Growth Score starten ↗</Link></div></div></header>
    <section className="section method-blueprint"><div className="container"><div className="method-blueprint-list">{growthMethod.map((step) => <article className="method-blueprint-row reveal" key={step.number}><span>{step.number}</span><div><small>Systemphase</small><h2>{step.name}</h2><p>{step.promise}</p></div><ul>{step.deliverables.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></div></section>
    <section className="section decision-section"><div className="container"><div className="split-heading"><div><span className="eyebrow reveal">Kein starrer Funnel</span><h2 className="section-title reveal">Wir starten dort,<br/><span className="serif">wo Wirkung verloren geht.</span></h2></div><p className="lead reveal">Nicht jede Marke braucht sofort Ads oder mehr Produktion. Das System zeigt, welcher Engpass zuerst gelöst werden muss und welche Schritte warten können.</p></div><div className="decision-grid">{[['Unklare Botschaft','Diagnose + Positionierung'],['Zu wenig Output','Creative System'],['Reichweite ohne Anfragen','Proof + Conversion'],['Kampagnen stagnieren','Creative Testing'],['Kein Überblick','Learning Loop']].map(([problem,solution])=><article className="decision-card reveal" key={problem}><span>Wenn …</span><h3>{problem}</h3><p>Startpunkt: {solution}</p></article>)}</div></div></section>
    <section className="premium-cta"><div className="container premium-cta-inner"><div><span className="eyebrow">Kostenlose Diagnose</span><h2>Finde zuerst den Engpass.<br/><span className="serif">Dann den richtigen Hebel.</span></h2></div><div><p>Der Social Growth Score dauert wenige Minuten und zeigt, welche Systemphase wahrscheinlich zuerst Aufmerksamkeit braucht.</p><Link className="btn btn-light-large" href="/social-media-audit">Score kostenlos starten ↗</Link></div></div></section></>
}
